#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
sl=1
while [ "$sl" -le 20 ]
do
	if [ "$sl" -eq 4 ]
	then
		echo "bad luch from China"
	elif [ "$sl" -eq 9 ]
	then
		echo "bad luck from Japan"
	else if [ "$sl" -eq 17 ]
	then 
		echo "bad luck from Italy"
	echo "$sl"
	fi 
	((sl++))
done

