#!/usr/bin/env bash

# Bash script that configures an Ubuntu server with the below requirements
sudo cp /etc/hosts /etc/hosts.bak
# Modify the hosts file
sudo sed -i 's/localhost/localhost 127.0.0.2/' /etc/hosts
sudo sed -i 's/facebook.com/8.8.8.8 facebook.com/' /etc/hosts
# Restart networking to apply changes
sudo systemctl restart networking
echo "Configuration complete."
